

<img src="<?=$assetsBaseUri ?>img/business-g0ec60ba24_1920.jpg" class="img-fluid position-relative top-50 start-50 translate-middle-x" alt="image coffee shop" width="800px" height="600px">
                    <p class="text-white fs-4 mt-5 px-5">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Porro, vel est dolores, odit ducimus similique voluptates, excepturi doloremque totam asperiores quasi. Aspernatur aliquid et accusantium aliquam in. Quibusdam, ratione impedit!Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec egestas eros ut orci lacinia, eget gravida enim posuere. Cras tincidunt urna sit amet purus faucibus ornare. Nam euismod elit vulputate purus venenatis, eget cursus est feugiat. Mauris sit amet pulvinar lorem, ac porta velit. Sed a placerat urna. Nam vitae fermentum quam. Donec nec magna in lectus lacinia sagittis. Nam fermentum hendrerit sollicitudin. Integer eu arcu sit amet nulla facilisis imperdiet. Cras vel enim tincidunt, imperdiet quam sed, lobortis nulla. Vestibulum condimentum lacus et ante congue imperdiet. Nulla ac ligula eget lacus ornare ullamcorper at a massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla pulvinar, arcu quis placerat sagittis, neque orci tristique lorem, sit amet venenatis nisi nunc id mi. Nulla dapibus bibendum diam, ut convallis enim pretium sed.
                    </p>
                    <p class="text-white fs-4 px-5">
                        Curabitur iaculis, turpis sit amet blandit luctus, dui nulla ornare mauris, eu ultrices elit eros egestas sem. Maecenas eget eleifend dolor. Etiam nec interdum neque. Vivamus posuere dolor erat, eget hendrerit mauris placerat commodo. Fusce pretium enim velit, a sodales odio fermentum sed. Ut nec sem a enim luctus bibendum. Ut posuere non ligula at sodales. Maecenas risus nibh, ullamcorper eu felis eget, vehicula accumsan nisi. Donec tellus enim, faucibus id pulvinar ut, iaculis vel tortor. Proin augue lorem, cursus sed placerat eu, convallis vitae ante. Fusce nec nunc ac arcu commodo scelerisque ut eget erat. Ut hendrerit vitae ipsum feugiat dapibus. Etiam porttitor vitae nulla at sagittis. Mauris convallis massa ante, id maximus enim porttitor varius. Suspendisse eget nibh mollis, condimentum erat in, tempus ligula.
                    </p>

                    <img src="<?=$assetsBaseUri ?>img/istockphoto-124954827-612x612.jpg" class="rounded-circle w-50 h-50 position-relative top-50 start-50 translate-middle-x mt-3 mb-3" alt="tasse à café">
            </main>