<div class="w-75 mt-5 position-relative start-50 top-50 translate-middle-x">
    <p class="text-white fs-4 px-5">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras enim diam, pharetra eu pulvinar ac, imperdiet et est. Praesent finibus tellus in lorem commodo vulputate. Nullam vestibulum maximus nulla, in pellentesque felis sollicitudin quis. Curabitur nisi dolor, ultrices non erat non, finibus accumsan ipsum. Integer convallis felis vitae velit laoreet rhoncus. Fusce dapibus quam sed dapibus tempor. Mauris interdum felis et ipsum vulputate, id sagittis massa suscipit. Sed lobortis pharetra enim a ullamcorper. Proin eleifend tincidunt urna, ut tincidunt libero.</br>

    Praesent eget porttitor mauris, a bibendum enim. Quisque in arcu in justo blandit tincidunt. Ut auctor rhoncus vehicula. Cras venenatis, erat ut tempus varius, libero nisl tristique augue, placerat malesuada dolor erat ac justo. Donec venenatis convallis felis non maximus. In interdum ante sed venenatis ornare. Ut ultrices felis id magna facilisis venenatis cursus id libero. Mauris maximus nulla ac sapien finibus lobortis. Morbi ullamcorper aliquam fringilla. Mauris ullamcorper efficitur mollis. Vivamus consequat ornare ligula, in varius eros commodo vitae. Fusce vel maximus ipsum, sed egestas ex. Nunc in volutpat nibh. Nullam tristique ac nulla nec volutpat. Nam non mauris ultricies, auctor mi in, posuere augue.</br>

    Proin tincidunt interdum sapien, id luctus justo condimentum sit amet. Fusce egestas vel ante sit amet malesuada. Nam dignissim elementum dui ac blandit. Fusce nibh risus, placerat in interdum et, lacinia vitae sem. In orci sem, efficitur commodo pulvinar sit amet, bibendum ac odio. Sed ullamcorper sed nulla a tempus. Quisque viverra varius metus eget convallis. Nulla interdum eleifend mi, volutpat congue tellus elementum et. Cras interdum fermentum purus sed convallis. Integer ut risus pharetra, pharetra mauris sed, fermentum enim. Donec ut ex sit amet enim gravida feugiat sed vel felis. Maecenas tempor ultrices nibh.</br>

    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam vehicula ullamcorper facilisis. Etiam condimentum ipsum maximus nibh lacinia, in molestie erat porttitor. Donec posuere, ex et porttitor ultrices, enim elit posuere sem, at porttitor urna nisl eu nisl. Aliquam rutrum ante ut nibh blandit ornare. Fusce quis elementum lacus. Fusce erat quam, vulputate sit amet leo eu, venenatis finibus lectus. Nulla nibh tellus, faucibus sed massa euismod, pellentesque hendrerit magna. Vestibulum placerat pretium arcu, quis ullamcorper metus malesuada eu. Nunc mollis enim at turpis accumsan, vitae rhoncus sapien iaculis.</br>

    Sed accumsan consequat blandit. Nam quis eros eros. Nunc suscipit urna et pulvinar suscipit. Sed non orci placerat, interdum arcu eget, placerat enim. Quisque porttitor ligula ac tempus consectetur. Nullam egestas metus urna, non placerat leo mollis non. Integer magna sapien, porta vitae felis a, varius condimentum tellus. Nam ac nulla venenatis, porttitor sapien ut, posuere nunc. Pellentesque mattis laoreet urna, id tempus mauris bibendum ac.
    </p>
</div>